# Value files for this Helm: https://hub.helm.sh/charts/mojo2600/pihole

image:
  tag: v5.1.1
  pullPolicy: Always

dnsmasq:
  customDnsEntries:
    - address=/ssnas/192.168.0.254

persistentVolumeClaim:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: "500Mi"

serviceTCP:
  type: LoadBalancer
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: pihole-svc

serviceUDP:
  type: LoadBalancer
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: pihole-svc

adminPassword: "admin"

DNS1: "8.8.8.8"
DNS2: "8.8.4.4"

hostNetwork: "false"
privileged: "false"

webHttp: "9080"
webHttps: "9443"